### ISSUE TITLE
MDK6的reset and run问题

### ISSUE THREAD

**Issue by xiaoyu200009** [jmjoy/study-stm32#1]
您好，在使用MDK6 vscode扩展时，发现在使用arm debugger下载程序时无法像uVision一样下载完成后自动运行（reset and run），而是需要手动reset以后代码才能开始运行，请问您后续找到解决方法了吗，感谢

**Comment by jmjoy** [comment]
我提过相关issue：https://github.com/ARM-software/vscode-keil-studio-pack/issues/25

但后续没有在 https://github.com/ARM-software/vscode-arm-debugger 上提新issue。

我现在觉得手动reset一下也没啥问题。

**Comment by xiaoyu200009** [comment]
感谢回复，目前板子上没有reset按键，只能通过断电的方式重新运行，希望后续官方插件可以支持一下

**Comment by jmjoy** [comment]
> 感谢回复，目前板子上没有reset按键，只能通过断电的方式重新运行，希望后续官方插件可以支持一下

我是将板子的Reset引脚连接按钮再接GND解决的。
